using Test
import SparseArrays: SparseMatrixCSC

include("lowlevel.jl")
include("basics.jl")

include("init.jl")

include("activeclass.jl")
include("bus.jl")
include("capacitors.jl")
include("capcontrols.jl")
include("circuit.jl")
include("cktelement.jl")
# include("ctrlqueue.jl")
include("element.jl")
include("executive.jl")
# include("progress.jl")
include("fuses.jl")
include("generators.jl")
include("isource.jl")
include("lines.jl")
include("loads.jl")
include("loadshape.jl")
include("meters.jl")  # commented out because of win32 failure
include("monitors.jl")
# include("parser.jl")
include("pdelements.jl")
include("pvsystems.jl")
include("reclosers.jl")
include("regcontrols.jl")
include("relays.jl")
# include("sensors.jl")
include("settings.jl")
include("solution.jl")
# include("swtcontrols.jl")
include("topology.jl")
include("transformers.jl")
include("vsources.jl")
include("xycurves.jl")  # commented out because of win32 failure
