export Close
export ComplexSeqCurrents
export ComplexSeqVoltages
export Currents
export CurrentsMagAng
export DisplayName
export DisplayName
export GUID
export Handle
export HasOCPDevice
export HasSwitchControl
export HasVoltControl
export IsIsolated
export IsOpen
export Losses
export MaxCurrent
export NodeOrder
export NodeRef
export NumConductors
export NumControllers
export NumPhases
export NumTerminals
export OCPDevice
export OCPDeviceIndex
export OCPDeviceType
export Open
export PhaseLosses
export Powers
export Residuals
export SeqCurrents
export SeqPowers
export SeqVoltages
export TotalPowers
export Voltages
export VoltagesMagAng
export YPrim
