export AccumulatedL
export EnergyMeter
export EnergyMeterName
export FromTerminal
export IsShunt
export Lambda
export NumCustomers
export ParentPDElement
export pctEmergency
export pctNormal
export SectionID
export TotalCustomers
export TotalKilometers
export TotalMiles
